// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArzntZPeyb4AzVPrqalTeJsRHNaRtj5Qc',
    appId: '1:848651881155:android:a35a2d6c490697a645b076',
    messagingSenderId: '848651881155',
    projectId: 'connect-doc-ba363',
    storageBucket: 'connect-doc-ba363.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9tyvY4eh8MvonP4CzgKg08Q1Q-JPD4vQ',
    appId: '1:848651881155:ios:bc6e5f69a77fa69f45b076',
    messagingSenderId: '848651881155',
    projectId: 'connect-doc-ba363',
    storageBucket: 'connect-doc-ba363.appspot.com',
    androidClientId:
        '848651881155-08shurqdbh6tlope9lnu0apav4j0klar.apps.googleusercontent.com',
    iosClientId:
        '848651881155-f58lb607n19fdqb07fsjk4219s9mbeme.apps.googleusercontent.com',
    iosBundleId: 'com.example.forAuth',
  );
}
